"""initial schema

Revision ID: 8ec96ff2bfcf
Revises: 
Create Date: 2026-03-12 19:20:45.204789
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8ec96ff2bfcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personality_traits', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_rules', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_palette', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accessories', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_name'), ['name'], unique=True)

    op.create_table('narrationvoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tone_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('narrationvoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrationvoice_key'), ['key'], unique=True)

    op.create_table('storyidea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('premise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setting', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bedtime_feeling', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('main_characters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supporting_characters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storyidea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storyidea_title'), ['title'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('storydraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_idea_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_time_minutes', sa.Integer(), nullable=False),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_idea_id'], ['storyidea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storydraft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storydraft_story_idea_id'), ['story_idea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storydraft_title'), ['title'], unique=False)

    op.create_table('userstoryprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_characters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_tones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_lengths', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_settings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_styles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_books_rated', sa.Integer(), nullable=False),
    sa.Column('total_books_completed', sa.Integer(), nullable=False),
    sa.Column('total_books_replayed', sa.Integer(), nullable=False),
    sa.Column('last_profile_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userstoryprofile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userstoryprofile_user_id'), ['user_id'], unique=True)

    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_draft_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age_band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('publication_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_draft_id'], ['storydraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_story_draft_id'), ['story_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_title'), ['title'], unique=False)

    op.create_table('storypage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_draft_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('characters_present', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('illustration_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_draft_id'], ['storydraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storypage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storypage_page_number'), ['page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_storypage_story_draft_id'), ['story_draft_id'], unique=False)

    op.create_table('bookaudio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.Column('script_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_audio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('approval_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['narrationvoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookaudio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookaudio_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookaudio_voice_id'), ['voice_id'], unique=False)

    op.create_table('bookpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('source_story_page_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('layout_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['source_story_page_id'], ['storypage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookpage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookpage_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookpage_page_number'), ['page_number'], unique=False)

    op.create_table('illustration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_page_id', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('approval_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_image_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_page_id'], ['storypage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('illustration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_illustration_story_page_id'), ['story_page_id'], unique=False)

    op.create_table('readingprogress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('current_page_number', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reader_identifier', 'book_id', name='uq_reader_book_progress')
    )
    with op.batch_alter_table('readingprogress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readingprogress_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_readingprogress_reader_identifier'), ['reader_identifier'], unique=False)

    op.create_table('userstoryfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('replayed', sa.Boolean(), nullable=False),
    sa.Column('preferred_character', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_tone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_book_feedback')
    )
    with op.batch_alter_table('userstoryfeedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userstoryfeedback_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_userstoryfeedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstoryfeedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userstoryfeedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_userstoryfeedback_book_id'))

    op.drop_table('userstoryfeedback')
    with op.batch_alter_table('readingprogress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readingprogress_reader_identifier'))
        batch_op.drop_index(batch_op.f('ix_readingprogress_book_id'))

    op.drop_table('readingprogress')
    with op.batch_alter_table('illustration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_illustration_story_page_id'))

    op.drop_table('illustration')
    with op.batch_alter_table('bookpage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookpage_page_number'))
        batch_op.drop_index(batch_op.f('ix_bookpage_book_id'))

    op.drop_table('bookpage')
    with op.batch_alter_table('bookaudio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookaudio_voice_id'))
        batch_op.drop_index(batch_op.f('ix_bookaudio_book_id'))

    op.drop_table('bookaudio')
    with op.batch_alter_table('storypage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storypage_story_draft_id'))
        batch_op.drop_index(batch_op.f('ix_storypage_page_number'))

    op.drop_table('storypage')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_title'))
        batch_op.drop_index(batch_op.f('ix_book_story_draft_id'))

    op.drop_table('book')
    with op.batch_alter_table('userstoryprofile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userstoryprofile_user_id'))

    op.drop_table('userstoryprofile')
    with op.batch_alter_table('storydraft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storydraft_title'))
        batch_op.drop_index(batch_op.f('ix_storydraft_story_idea_id'))

    op.drop_table('storydraft')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('storyidea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storyidea_title'))

    op.drop_table('storyidea')
    with op.batch_alter_table('narrationvoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrationvoice_key'))

    op.drop_table('narrationvoice')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_name'))

    op.drop_table('character')
    # ### end Alembic commands ###
